<?php

use Botble\Theme\Facades\Theme;
use Botble\Theme\Theme as BaseTheme;

app()->booted(function () {
    if (! method_exists(BaseTheme::class, 'registerThemeIconFields')) {
        return;
    }

    $icons = [
        'feather icon icon-alert-octagon',
        'feather icon icon-alert-circle',
        'feather icon icon-activity',
        'feather icon icon-alert-triangle',
        'feather icon icon-align-center',
        'feather icon icon-airplay',
        'feather icon icon-align-justify',
        'feather icon icon-align-left',
        'feather icon icon-align-right',
        'feather icon icon-arrow-down-left',
        'feather icon icon-arrow-down-right',
        'feather icon icon-anchor',
        'feather icon icon-aperture',
        'feather icon icon-arrow-left',
        'feather icon icon-arrow-right',
        'feather icon icon-arrow-down',
        'feather icon icon-arrow-up-left',
        'feather icon icon-arrow-up-right',
        'feather icon icon-arrow-up',
        'feather icon icon-award',
        'feather icon icon-bar-chart',
        'feather icon icon-at-sign',
        'feather icon icon-bar-chart-2',
        'feather icon icon-battery-charging',
        'feather icon icon-bell-off',
        'feather icon icon-battery',
        'feather icon icon-bluetooth',
        'feather icon icon-bell',
        'feather icon icon-book',
        'feather icon icon-briefcase',
        'feather icon icon-camera-off',
        'feather icon icon-calendar',
        'feather icon icon-bookmark',
        'feather icon icon-box',
        'feather icon icon-camera',
        'feather icon icon-check-circle',
        'feather icon icon-check',
        'feather icon icon-check-square',
        'feather icon icon-cast',
        'feather icon icon-chevron-down',
        'feather icon icon-chevron-left',
        'feather icon icon-chevron-right',
        'feather icon icon-chevron-up',
        'feather icon icon-chevrons-down',
        'feather icon icon-chevrons-right',
        'feather icon icon-chevrons-up',
        'feather icon icon-chevrons-left',
        'feather icon icon-circle',
        'feather icon icon-clipboard',
        'feather icon icon-chrome',
        'feather icon icon-clock',
        'feather icon icon-cloud-lightning',
        'feather icon icon-cloud-drizzle',
        'feather icon icon-cloud-rain',
        'feather icon icon-cloud-off',
        'feather icon icon-codepen',
        'feather icon icon-cloud-snow',
        'feather icon icon-compass',
        'feather icon icon-copy',
        'feather icon icon-corner-down-right',
        'feather icon icon-corner-down-left',
        'feather icon icon-corner-left-down',
        'feather icon icon-corner-left-up',
        'feather icon icon-corner-up-left',
        'feather icon icon-corner-up-right',
        'feather icon icon-corner-right-down',
        'feather icon icon-corner-right-up',
        'feather icon icon-cpu',
        'feather icon icon-credit-card',
        'feather icon icon-crosshair',
        'feather icon icon-disc',
        'feather icon icon-delete',
        'feather icon icon-download-cloud',
        'feather icon icon-download',
        'feather icon icon-droplet',
        'feather icon icon-edit-2',
        'feather icon icon-edit',
        'feather icon icon-edit-1',
        'feather icon icon-external-link',
        'feather icon icon-eye',
        'feather icon icon-feather',
        'feather icon icon-facebook',
        'feather icon icon-file-minus',
        'feather icon icon-eye-off',
        'feather icon icon-fast-forward',
        'feather icon icon-file-text',
        'feather icon icon-film',
        'feather icon icon-file',
        'feather icon icon-file-plus',
        'feather icon icon-folder',
        'feather icon icon-filter',
        'feather icon icon-flag',
        'feather icon icon-globe',
        'feather icon icon-grid',
        'feather icon icon-heart',
        'feather icon icon-home',
        'feather icon icon-github',
        'feather icon icon-image',
        'feather icon icon-inbox',
        'feather icon icon-layers',
        'feather icon icon-info',
        'feather icon icon-instagram',
        'feather icon icon-layout',
        'feather icon icon-link-2',
        'feather icon icon-life-buoy',
        'feather icon icon-link',
        'feather icon icon-log-in',
        'feather icon icon-list',
        'feather icon icon-lock',
        'feather icon icon-log-out',
        'feather icon icon-loader',
        'feather icon icon-mail',
        'feather icon icon-maximize-2',
        'feather icon icon-map',
        'feather icon icon-map-pin',
        'feather icon icon-menu',
        'feather icon icon-message-circle',
        'feather icon icon-message-square',
        'feather icon icon-minimize-2',
        'feather icon icon-mic-off',
        'feather icon icon-minus-circle',
        'feather icon icon-mic',
        'feather icon icon-minus-square',
        'feather icon icon-minus',
        'feather icon icon-moon',
        'feather icon icon-monitor',
        'feather icon icon-more-vertical',
        'feather icon icon-more-horizontal',
        'feather icon icon-move',
        'feather icon icon-music',
        'feather icon icon-navigation-2',
        'feather icon icon-navigation',
        'feather icon icon-octagon',
        'feather icon icon-package',
        'feather icon icon-pause-circle',
        'feather icon icon-pause',
        'feather icon icon-percent',
        'feather icon icon-phone-call',
        'feather icon icon-phone-forwarded',
        'feather icon icon-phone-missed',
        'feather icon icon-phone-off',
        'feather icon icon-phone-incoming',
        'feather icon icon-phone',
        'feather icon icon-phone-outgoing',
        'feather icon icon-pie-chart',
        'feather icon icon-play-circle',
        'feather icon icon-play',
        'feather icon icon-plus-square',
        'feather icon icon-plus-circle',
        'feather icon icon-plus',
        'feather icon icon-pocket',
        'feather icon icon-printer',
        'feather icon icon-power',
        'feather icon icon-radio',
        'feather icon icon-repeat',
        'feather icon icon-refresh-ccw',
        'feather icon icon-rewind',
        'feather icon icon-rotate-ccw',
        'feather icon icon-refresh-cw',
        'feather icon icon-rotate-cw',
        'feather icon icon-save',
        'feather icon icon-search',
        'feather icon icon-server',
        'feather icon icon-scissors',
        'feather icon icon-share-2',
        'feather icon icon-share',
        'feather icon icon-shield',
        'feather icon icon-settings',
        'feather icon icon-skip-back',
        'feather icon icon-shuffle',
        'feather icon icon-sidebar',
        'feather icon icon-skip-forward',
        'feather icon icon-slack',
        'feather icon icon-slash',
        'feather icon icon-smartphone',
        'feather icon icon-square',
        'feather icon icon-speaker',
        'feather icon icon-star',
        'feather icon icon-stop-circle',
        'feather icon icon-sun',
        'feather icon icon-sunrise',
        'feather icon icon-tablet',
        'feather icon icon-tag',
        'feather icon icon-sunset',
        'feather icon icon-target',
        'feather icon icon-thermometer',
        'feather icon icon-thumbs-up',
        'feather icon icon-thumbs-down',
        'feather icon icon-toggle-left',
        'feather icon icon-toggle-right',
        'feather icon icon-trash-2',
        'feather icon icon-trash',
        'feather icon icon-trending-up',
        'feather icon icon-trending-down',
        'feather icon icon-triangle',
        'feather icon icon-type',
        'feather icon icon-twitter',
        'feather icon icon-upload',
        'feather icon icon-umbrella',
        'feather icon icon-upload-cloud',
        'feather icon icon-unlock',
        'feather icon icon-user-check',
        'feather icon icon-user-minus',
        'feather icon icon-user-plus',
        'feather icon icon-user-x',
        'feather icon icon-user',
        'feather icon icon-users',
        'feather icon icon-video-off',
        'feather icon icon-video',
        'feather icon icon-voicemail',
        'feather icon icon-volume-x',
        'feather icon icon-volume-2',
        'feather icon icon-volume-1',
        'feather icon icon-volume',
        'feather icon icon-watch',
        'feather icon icon-wifi',
        'feather icon icon-x-square',
        'feather icon icon-wind',
        'feather icon icon-x',
        'feather icon icon-x-circle',
        'feather icon icon-zap',
        'feather icon icon-zoom-in',
        'feather icon icon-zoom-out',
        'feather icon icon-command',
        'feather icon icon-cloud',
        'feather icon icon-hash',
        'feather icon icon-headphones',
        'feather icon icon-underline',
        'feather icon icon-italic',
        'feather icon icon-bold',
        'feather icon icon-crop',
        'feather icon icon-help-circle',
        'feather icon icon-paperclip',
        'feather icon icon-shopping-cart',
        'feather icon icon-tv',
        'feather icon icon-wifi-off',
        'feather icon icon-minimize',
        'feather icon icon-maximize',
        'feather icon icon-gitlab',
        'feather icon icon-sliders',
        'feather icon icon-star-on',
        'feather icon icon-heart-on',
        'feather icon icon-archive',
        'feather icon icon-arrow-down-circle',
        'feather icon icon-arrow-up-circle',
        'feather icon icon-arrow-left-circle',
        'feather icon icon-arrow-right-circle',
        'feather icon icon-bar-chart-line-',
        'feather icon icon-bar-chart-line',
        'feather icon icon-book-open',
        'feather icon icon-code',
        'feather icon icon-database',
        'feather icon icon-dollar-sign',
        'feather icon icon-folder-plus',
        'feather icon icon-gift',
        'feather icon icon-folder-minus',
        'feather icon icon-git-commit',
        'feather icon icon-git-branch',
        'feather icon icon-git-pull-request',
        'feather icon icon-git-merge',
        'feather icon icon-linkedin',
        'feather icon icon-hard-drive',
        'feather icon icon-more-vertical-',
        'feather icon icon-more-horizontal-',
        'feather icon icon-rss',
        'feather icon icon-send',
        'feather icon icon-shield-off',
        'feather icon icon-shopping-bag',
        'feather icon icon-terminal',
        'feather icon icon-truck',
        'feather icon icon-zap-off',
        'feather icon icon-youtube',
        'fab fa-500px',
        'fab fa-accessible-icon',
        'fab fa-accusoft',
        'fab fa-acquisitions-incorporated',
        'fab fa-adn',
        'fab fa-adversal',
        'fab fa-affiliatetheme',
        'fab fa-airbnb',
        'fab fa-algolia',
        'fab fa-alipay',
        'fab fa-amazon-pay',
        'fab fa-amazon',
        'fab fa-amilia',
        'fab fa-android',
        'fab fa-angellist',
        'fab fa-angrycreative',
        'fab fa-angular',
        'fab fa-app-store-ios',
        'fab fa-app-store',
        'fab fa-apper',
        'fab fa-apple-pay',
        'fab fa-apple',
        'fab fa-artstation',
        'fab fa-asymmetrik',
        'fab fa-atlassian',
        'fab fa-audible',
        'fab fa-autoprefixer',
        'fab fa-avianex',
        'fab fa-aviato',
        'fab fa-aws',
        'fab fa-bandcamp',
        'fab fa-battle-net',
        'fab fa-behance-square',
        'fab fa-behance',
        'fab fa-bimobject',
        'fab fa-bitbucket',
        'fab fa-bitcoin',
        'fab fa-bity',
        'fab fa-black-tie',
        'fab fa-blackberry',
        'fab fa-blogger-b',
        'fab fa-blogger',
        'fab fa-bluetooth-b',
        'fab fa-bluetooth',
        'fab fa-bootstrap',
        'fab fa-btc',
        'fab fa-buffer',
        'fab fa-buromobelexperte',
        'fa fa-buy-n-large',
        'fab fa-buysellads',
        'fab fa-canadian-maple-leaf',
        'fab fa-cc-amazon-pay',
        'fab fa-cc-amex',
        'fab fa-cc-apple-pay',
        'fab fa-cc-diners-club',
        'fab fa-cc-discover',
        'fab fa-cc-jcb',
        'fab fa-cc-mastercard',
        'fab fa-cc-paypal',
        'fab fa-cc-stripe',
        'fab fa-cc-visa',
        'fab fa-centercode',
        'fab fa-centos',
        'fab fa-chrome',
        'fab fa-chromecast',
        'fa fa-cloudflare',
        'fab fa-cloudscale',
        'fab fa-cloudsmith',
        'fab fa-cloudversify',
        'fab fa-codepen',
        'fab fa-codiepie',
        'fab fa-confluence',
        'fab fa-connectdevelop',
        'fab fa-contao',
        'fab fa-cotton-bureau',
        'fab fa-cpanel',
        'fab fa-creative-commons-by',
        'fab fa-creative-commons-nc-eu',
        'fab fa-creative-commons-nc-jp',
        'fab fa-creative-commons-nc',
        'fab fa-creative-commons-nd',
        'fab fa-creative-commons-pd-alt',
        'fab fa-creative-commons-pd',
        'fab fa-creative-commons-remix',
        'fab fa-creative-commons-sa',
        'fab fa-creative-commons-sampling-plus',
        'fab fa-creative-commons-sampling',
        'fab fa-creative-commons-share',
        'fab fa-creative-commons-zero',
        'fab fa-creative-commons',
        'fab fa-critical-role',
        'fab fa-css3-alt',
        'fab fa-css3',
        'fab fa-cuttlefish',
        'fab fa-d-and-d-beyond',
        'fab fa-d-and-d',
        'fa fa-dailymotion',
        'fab fa-dashcube',
        'fa fa-deezer',
        'fab fa-delicious',
        'fab fa-deploydog',
        'fab fa-deskpro',
        'fab fa-dev',
        'fab fa-deviantart',
        'fab fa-dhl',
        'fab fa-diaspora',
        'fab fa-digg',
        'fab fa-digital-ocean',
        'fab fa-discord',
        'fab fa-discourse',
        'fab fa-dochub',
        'fab fa-docker',
        'fab fa-draft2digital',
        'fab fa-dribbble-square',
        'fab fa-dribbble',
        'fab fa-dropbox',
        'fab fa-drupal',
        'fab fa-dyalog',
        'fab fa-earlybirds',
        'fab fa-ebay',
        'fab fa-edge',
        'fab fa-elementor',
        'fab fa-ello',
        'fab fa-ember',
        'fab fa-empire',
        'fab fa-envira',
        'fab fa-erlang',
        'fab fa-ethereum',
        'fab fa-etsy',
        'fab fa-evernote',
        'fab fa-expeditedssl',
        'fab fa-facebook-f',
        'fab fa-facebook-messenger',
        'fab fa-facebook-square',
        'fa fa-facebook',
        'fab fa-fantasy-flight-games',
        'fab fa-fedex',
        'fab fa-fedora',
        'fab fa-figma',
        'fab fa-firefox',
        'fab fa-first-order-alt',
        'fab fa-first-order',
        'fab fa-firstdraft',
        'fab fa-flickr',
        'fab fa-flipboard',
        'fab fa-fly',
        'fab fa-font-awesome-alt',
        'fab fa-font-awesome-flag',
        'fa fa-font-awesome-logo-full',
        'fab fa-font-awesome',
        'fab fa-fonticons-fi',
        'fab fa-fonticons',
        'fab fa-fort-awesome-alt',
        'fab fa-fort-awesome',
        'fab fa-forumbee',
        'fab fa-foursquare',
        'fab fa-free-code-camp',
        'fab fa-freebsd',
        'fab fa-fulcrum',
        'fab fa-galactic-republic',
        'fab fa-galactic-senate',
        'fab fa-get-pocket',
        'fab fa-gg-circle',
        'fab fa-gg',
        'fab fa-git-alt',
        'fab fa-git-square',
        'fab fa-git',
        'fab fa-github-alt',
        'fab fa-github-square',
        'fab fa-github',
        'fab fa-gitkraken',
        'fab fa-gitlab',
        'fab fa-gitter',
        'fab fa-glide-g',
        'fab fa-glide',
        'fab fa-gofore',
        'fab fa-goodreads-g',
        'fab fa-goodreads',
        'fab fa-google-drive',
        'fab fa-google-plus-g',
        'fab fa-google-plus-square',
        'fab fa-google-plus',
        'fab fa-google-wallet',
        'fab fa-google',
        'fab fa-gratipay',
        'fab fa-grav',
        'fab fa-gripfire',
        'fab fa-grunt',
        'fab fa-gulp',
        'fab fa-hacker-news-square',
        'fab fa-hacker-news',
        'fab fa-hackerrank',
        'fab fa-hips',
        'fab fa-hire-a-helper',
        'fab fa-hooli',
        'fab fa-hornbill',
        'fab fa-hotjar',
        'fab fa-houzz',
        'fab fa-html5',
        'fab fa-hubspot',
        'fab fa-imdb',
        'fa fa-instagram',
        'fab fa-intercom',
        'fab fa-internet-explorer',
        'fab fa-invision',
        'fab fa-ioxhost',
        'fab fa-itch-io',
        'fab fa-itunes-note',
        'fab fa-itunes',
        'fab fa-java',
        'fab fa-jedi-order',
        'fab fa-jenkins',
        'fab fa-jira',
        'fab fa-joget',
        'fab fa-joomla',
        'fab fa-js-square',
        'fab fa-js',
        'fab fa-jsfiddle',
        'fab fa-kaggle',
        'fab fa-keybase',
        'fab fa-keycdn',
        'fab fa-kickstarter-k',
        'fab fa-kickstarter',
        'fab fa-korvue',
        'fab fa-laravel',
        'fab fa-lastfm-square',
        'fab fa-lastfm',
        'fab fa-leanpub',
        'fab fa-less',
        'fab fa-line',
        'fab fa-linkedin-in',
        'fa fa-linkedin',
        'fab fa-linode',
        'fab fa-linux',
        'fab fa-lyft',
        'fab fa-magento',
        'fab fa-mailchimp',
        'fab fa-mandalorian',
        'fab fa-markdown',
        'fab fa-mastodon',
        'fab fa-maxcdn',
        'fab fa-medapps',
        'fab fa-medium-m',
        'fab fa-medium',
        'fab fa-medrt',
        'fab fa-meetup',
        'fab fa-megaport',
        'fab fa-mendeley',
        'fab fa-microsoft',
        'fab fa-mix',
        'fab fa-mixcloud',
        'fab fa-mizuni',
        'fab fa-modx',
        'fab fa-monero',
        'fab fa-napster',
        'fab fa-neos',
        'fab fa-nimblr',
        'fab fa-node-js',
        'fab fa-node',
        'fab fa-npm',
        'fab fa-ns8',
        'fab fa-nutritionix',
        'fab fa-odnoklassniki-square',
        'fab fa-odnoklassniki',
        'fab fa-old-republic',
        'fab fa-opencart',
        'fab fa-openid',
        'fab fa-opera',
        'fab fa-optin-monster',
        'fab fa-osi',
        'fab fa-page4',
        'fab fa-pagelines',
        'fab fa-palfed',
        'fab fa-patreon',
        'fab fa-paypal',
        'fab fa-penny-arcade',
        'fab fa-periscope',
        'fab fa-phabricator',
        'fab fa-phoenix-framework',
        'fab fa-phoenix-squadron',
        'fab fa-php',
        'fab fa-pied-piper-alt',
        'fab fa-pied-piper-hat',
        'fab fa-pied-piper-pp',
        'fab fa-pied-piper',
        'fab fa-pinterest-p',
        'fab fa-pinterest-square',
        'fa fa-pinterest',
        'fab fa-playstation',
        'fab fa-product-hunt',
        'fab fa-pushed',
        'fab fa-python',
        'fab fa-qq',
        'fab fa-quinscape',
        'fab fa-quora',
        'fab fa-r-project',
        'fab fa-raspberry-pi',
        'fab fa-ravelry',
        'fab fa-react',
        'fab fa-reacteurope',
        'fab fa-readme',
        'fab fa-rebel',
        'fab fa-red-river',
        'fab fa-reddit-alien',
        'fab fa-reddit-square',
        'fab fa-reddit',
        'fab fa-redhat',
        'fab fa-renren',
        'fab fa-replyd',
        'fab fa-researchgate',
        'fab fa-resolving',
        'fab fa-rev',
        'fab fa-rocketchat',
        'fab fa-rockrms',
        'fab fa-safari',
        'fab fa-salesforce',
        'fab fa-sass',
        'fab fa-schlix',
        'fab fa-scribd',
        'fab fa-searchengin',
        'fab fa-sellcast',
        'fab fa-sellsy',
        'fab fa-servicestack',
        'fab fa-shirtsinbulk',
        'fab fa-shopware',
        'fab fa-simplybuilt',
        'fab fa-sistrix',
        'fab fa-sith',
        'fab fa-sketch',
        'fab fa-skyatlas',
        'fab fa-skype',
        'fab fa-slack-hash',
        'fab fa-slack',
        'fab fa-slideshare',
        'fab fa-snapchat-ghost',
        'fab fa-snapchat-square',
        'fab fa-snapchat',
        'fab fa-soundcloud',
        'fab fa-sourcetree',
        'fab fa-speakap',
        'fab fa-speaker-deck',
        'fab fa-spotify',
        'fab fa-squarespace',
        'fab fa-stack-exchange',
        'fab fa-stack-overflow',
        'fab fa-stackpath',
        'fab fa-staylinked',
        'fab fa-steam-square',
        'fab fa-steam-symbol',
        'fab fa-steam',
        'fab fa-sticker-mule',
        'fab fa-strava',
        'fab fa-stripe-s',
        'fab fa-stripe',
        'fab fa-studiovinari',
        'fab fa-stumbleupon-circle',
        'fab fa-stumbleupon',
        'fab fa-superpowers',
        'fab fa-supple',
        'fab fa-suse',
        'fa fa-swift',
        'fab fa-symfony',
        'fab fa-teamspeak',
        'fab fa-telegram-plane',
        'fab fa-telegram',
        'fab fa-tencent-weibo',
        'fab fa-the-red-yeti',
        'fab fa-themeco',
        'fab fa-themeisle',
        'fab fa-think-peaks',
        'fab fa-trade-federation',
        'fab fa-trello',
        'fab fa-tripadvisor',
        'fab fa-tumblr-square',
        'fab fa-tumblr',
        'fab fa-twitch',
        'fab fa-twitter-square',
        'fa fa-twitter',
        'fab fa-typo3',
        'fab fa-uber',
        'fab fa-ubuntu',
        'fab fa-uikit',
        'fab fa-uniregistry',
        'fab fa-untappd',
        'fab fa-ups',
        'fab fa-usb',
        'fab fa-usps',
        'fab fa-ussunnah',
        'fab fa-vaadin',
        'fab fa-viacoin',
        'fab fa-viadeo-square',
        'fab fa-viadeo',
        'fab fa-viber',
        'fab fa-vimeo-square',
        'fab fa-vimeo-v',
        'fab fa-vimeo',
        'fab fa-vine',
        'fab fa-vk',
        'fab fa-vnv',
        'fab fa-vuejs',
        'fab fa-waze',
        'fab fa-weebly',
        'fab fa-weibo',
        'fab fa-weixin',
        'fab fa-whatsapp-square',
        'fab fa-whatsapp',
        'fab fa-whmcs',
        'fab fa-wikipedia-w',
        'fab fa-windows',
        'fab fa-wix',
        'fab fa-wizards-of-the-coast',
        'fab fa-wolf-pack-battalion',
        'fab fa-wordpress-simple',
        'fab fa-wordpress',
        'fab fa-wpbeginner',
        'fab fa-wpexplorer',
        'fab fa-wpforms',
        'fab fa-wpressr',
        'fab fa-xbox',
        'fab fa-xing-square',
        'fab fa-xing',
        'fab fa-y-combinator',
        'fab fa-yahoo',
        'fab fa-yammer',
        'fab fa-yandex-international',
        'fab fa-yandex',
        'fab fa-yarn',
        'fab fa-yelp',
        'fab fa-yoast',
        'fa fa-youtube-square',
        'fa fa-youtube',
        'fab fa-zhihu',
        'icon-tiktok',
    ];

    $css = [
        Theme::asset()->url('fonts/feather-font/css/iconfont.css'),
        Theme::asset()->url('plugins/font-awesome/css/font-awesome.min.css'),
    ];

    Theme::registerThemeIconFields($icons, $css);
});
